# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2aac7f5d-fe4b-45e0-abe1-44f76426c3f1";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-2aac7f5d-fe4b-45e0-abe1-44f76426c3f1".device = "/dev/disk/by-uuid/2aac7f5d-fe4b-45e0-abe1-44f76426c3f1";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-2aac7f5d-fe4b-45e0-abe1-44f76426c3f1";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-2aac7f5d-fe4b-45e0-abe1-44f76426c3f1";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EA32-ABD9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-38a4207f-6ae6-4333-8e9e-6d8cbe258ac0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
