# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  imports = [ ./hardware-configuration.nix ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9f5f5c3e-1d84-4622-b606-ce2fb4030811";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9f5f5c3e-1d84-4622-b606-ce2fb4030811".device = "/dev/disk/by-uuid/9f5f5c3e-1d84-4622-b606-ce2fb4030811";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4B62-2DD9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-091aad14-94e8-4ef8-b53a-1493f3dfe3b6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
